### ISSUE TITLE
关于Dagger2的问题

### ISSUE THREAD

**Issue by Ztiany** [Piasy/YaMvp#1]
YaMvpDiActivity中是在onCreate中调用的initializeDi方法来初始化容器，然后在YaMvpDiFragment中会调用 `C component = ((HasComponent<C>) getActivity()).getComponent(); mPresenter = component.presenter();`来获取Activity提供的容器进行注入。

正常情况下没有什么问题，但是使用屏幕旋转来模拟Activity在后台被销毁然后重新进入界面的话可能会造成空指针异常。因为Activity重建的时候其onCreate方法在其内部的Fragment的onCreate方法之后执行。

**Comment by Piasy** [comment]
谢谢指出！

我在 README 的最后有提到：

> Activity/Fragment kill and restore are not considered yet.

这块我还没有考虑到，后面再想想怎么处理比较好。

**Comment by Ztiany** [comment]
哈哈，好吧，我没有看到。我现在就是遇到这样的问题，就是想请教一下你是否有解决的方法。

我现在的做法是在Fragment的onActivityCreate方法中获取Activity的Component进行注入的，然而因为我一般使用单Activity+多Fragment实现的各个功能模块，所以在Fragment切换的时候其onActivityCreate会多次调用，所以很多时候还要加上判断防止Fragment多次注入。也是比较繁琐的。

我在考虑是否可以在Activity的构造代码块中就初始化容器，比较此时的Componen也只是需要拿到Activity的应用而已。

**Comment by Piasy** [comment]
fixed by b9773d24aebe824d9263b8658e03dcf46f40121c
