### ISSUE TITLE
About YaRxDelegate

### ISSUE THREAD

**Issue by asker517** [Piasy/YaMvp#2]
很棒的MVP方式,想请教一下您在`YaRxDelegate`中`mSubscriptions2Stop`和`mSubscriptions2Destroy`这两个`CompositeSubscription`在使用中具体的区别是怎么样子的呢?或者可否简单描述一下使用场景呢?

**Comment by Piasy** [comment]
谢谢！

addUtilStop 适用于在 pause 之后要停止监听（取消订阅），在 resume 的时候继续监听的场景。具体例子就看业务需求了。

**Comment by asker517** [comment]
@Piasy OK 感谢
