### ISSUE TITLE
关于fragment

### ISSUE THREAD

**Issue by fflamingogo** [Piasy/YaMvp#3]
大神，这套mvp强制要使用fragment，我个人不太喜欢用fragment，能说说用fragment的原因吗

**Comment by Piasy** [comment]
Google 官方强调 favor Fragment over Activity。

不过确实这里对 DI 以及 Fragment/Activity 的处理不是很好，需要优化，但我最近没时间弄这块了，抱歉。

**Comment by fflamingogo** [comment]
明白3q
